### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by Zargess** [sqeezy/FibonacciHeap#1]
I really like your implementation. Would you make this into a nuget package, both for normal .net and .net core?

**Comment by sqeezy** [comment]
I will look into it for sure. I'm honestly pretty surprised that someone
wants my implementation.
As for dotnet core, the project system will get changed in V 1.1 and it
would be additional work to change the NuGet package again. I will still
evaluate doing it.

Marcus Haagh notifications@github.com schrieb am Sa., 27. Aug. 2016 09:30:

**Comment by sqeezy** [comment]
I just pushed a first version to NuGet. Feel free to send me more requests.
https://www.nuget.org/packages/FibonacciHeap/
