### ISSUE TITLE
Test more platforms 

### ISSUE THREAD

**Issue by sqeezy** [sqeezy/FibonacciHeap#10]
At the moment only windows and Linux is tested. It would be good to at least have OSX im addition. Maybe even different Linux flavors.

**Comment by jmschuaquico** [comment]
I'm using this in Unity3D, I could probably post whether it compiles on other platforms (OSX, iOS, Android) later.

**Comment by sqeezy** [comment]
I think we can just do that with travis.ci
I'm not sure whether linux platforms diversity is important, as this is a pretty hardware independent library.
